[2025-01-11 16:57:13,476][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-01-11 16:57:13,478][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-01-11 16:57:13,503][__main__][INFO] - Instantiating datamodule <src.data.custom_datamodule.T3ALDataModule>
[2025-01-11 16:57:13,506][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
          ^^^^^^^^^^^^^^^^^^
AttributeError: module 'src.data' has no attribute 'custom_datamodule'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
          ^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/def/fewshot/src/data/custom_datamodule.py", line 5, in <module>
    from src.data.components.dataset import T3ALDataset
  File "/home/def/fewshot/src/data/components/dataset.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
             ^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/utils.py", line 653, in _locate
    raise ImportError(
ImportError: Error loading 'src.data.custom_datamodule.T3ALDataModule':
ModuleNotFoundError("No module named 'pandas'")
Are you sure that 'custom_datamodule' is importable from module 'src.data'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/def/fewshot/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/train.py", line 54, in train
    datamodule: LightningDataModule = hydra.utils.instantiate(cfg.data)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'src.data.custom_datamodule.T3ALDataModule', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: data
[2025-01-11 16:57:13,508][src.utils.utils][INFO] - Output dir: /home/def/fewshot/logs/train/runs/2025-01-11_16-57-13
[2025-01-11 16:57:47,829][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-01-11 16:57:47,831][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-01-11 16:57:47,852][__main__][INFO] - Instantiating datamodule <src.data.custom_datamodule.T3ALDataModule>
[2025-01-11 16:57:48,204][__main__][INFO] - Instantiating model <src.models.tt_method_module.T3ALModule>
[2025-01-11 16:57:48,647][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
          ^^^^^^^^^^^^^^^^^^
AttributeError: module 'src.models' has no attribute 'tt_method_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
          ^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/def/fewshot/src/models/tt_method_module.py", line 8, in <module>
    from src.evaluate import evaluate
  File "/home/def/fewshot/src/evaluate.py", line 8, in <module>
    from tabulate import tabulate
ModuleNotFoundError: No module named 'tabulate'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
             ^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/utils.py", line 653, in _locate
    raise ImportError(
ImportError: Error loading 'src.models.tt_method_module.T3ALModule':
ModuleNotFoundError("No module named 'tabulate'")
Are you sure that 'tt_method_module' is importable from module 'src.models'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/def/fewshot/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/train.py", line 57, in train
    model: LightningModule = hydra.utils.instantiate(cfg.model)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'src.models.tt_method_module.T3ALModule', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: model
[2025-01-11 16:57:48,649][src.utils.utils][INFO] - Output dir: /home/def/fewshot/logs/train/runs/2025-01-11_16-57-47
[2025-01-11 16:58:37,384][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-01-11 16:58:37,386][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-01-11 16:58:37,409][__main__][INFO] - Instantiating datamodule <src.data.custom_datamodule.T3ALDataModule>
[2025-01-11 16:58:37,667][__main__][INFO] - Instantiating model <src.models.tt_method_module.T3ALModule>
[2025-01-11 16:58:38,421][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: T3ALNet.__init__() missing 1 required positional argument: 'avg_features_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/def/fewshot/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/train.py", line 57, in train
    model: LightningModule = hydra.utils.instantiate(cfg.model)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
            ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'src.models.components.tt_method.T3ALNet':
TypeError("T3ALNet.__init__() missing 1 required positional argument: 'avg_features_path'")
full_key: model.net
[2025-01-11 16:58:38,422][src.utils.utils][INFO] - Output dir: /home/def/fewshot/logs/train/runs/2025-01-11_16-58-37
[2025-01-11 17:03:27,561][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-01-11 17:03:27,564][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-01-11 17:03:27,588][__main__][INFO] - Instantiating datamodule <src.data.custom_datamodule.T3ALDataModule>
[2025-01-11 17:03:27,854][__main__][INFO] - Instantiating model <src.models.tt_method_module.T3ALModule>
[2025-01-11 17:03:28,566][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: T3ALNet.__init__() missing 1 required positional argument: 'avg_features_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/def/fewshot/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/train.py", line 57, in train
    model: LightningModule = hydra.utils.instantiate(cfg.model)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
            ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'src.models.components.tt_method.T3ALNet':
TypeError("T3ALNet.__init__() missing 1 required positional argument: 'avg_features_path'")
full_key: model.net
[2025-01-11 17:03:28,567][src.utils.utils][INFO] - Output dir: /home/def/fewshot/logs/train/runs/2025-01-11_17-03-27
[2025-01-11 17:10:43,684][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-01-11 17:10:43,687][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-01-11 17:10:43,717][__main__][INFO] - Instantiating datamodule <src.data.custom_datamodule.T3ALDataModule>
[2025-01-11 17:10:44,187][__main__][INFO] - Instantiating model <src.models.tt_method_module.T3ALModule>
[2025-01-11 17:10:45,127][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: T3ALNet.__init__() missing 1 required positional argument: 'avg_features_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/def/fewshot/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/train.py", line 57, in train
    model: LightningModule = hydra.utils.instantiate(cfg.model)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
            ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'src.models.components.tt_method.T3ALNet':
TypeError("T3ALNet.__init__() missing 1 required positional argument: 'avg_features_path'")
full_key: model.net
[2025-01-11 17:10:45,128][src.utils.utils][INFO] - Output dir: /home/def/fewshot/logs/train/runs/2025-01-11_17-10-43
[2025-01-11 17:22:21,427][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-01-11 17:22:21,430][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-01-11 17:22:21,458][__main__][INFO] - Instantiating datamodule <src.data.custom_datamodule.T3ALDataModule>
[2025-01-11 17:22:21,933][__main__][INFO] - Instantiating model <src.models.tt_method_module.T3ALModule>
[2025-01-11 17:22:22,893][root][INFO] - Loaded coca_ViT-L-14 model config.
[2025-01-11 17:22:26,529][root][INFO] - Loading pretrained coca_ViT-L-14 weights (mscoco_finetuned_laion2B-s13B-b90k).
[2025-01-11 17:22:27,982][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/models/components/tt_method.py", line 83, in __init__
    self.video_dir = os.path.join(self.video_path, "Thumos14/videos/")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/def/fewshot/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/train.py", line 57, in train
    model: LightningModule = hydra.utils.instantiate(cfg.model)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
            ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'src.models.components.tt_method.T3ALNet':
TypeError('expected str, bytes or os.PathLike object, not NoneType')
full_key: model.net
[2025-01-11 17:22:27,984][src.utils.utils][INFO] - Output dir: /home/def/fewshot/logs/train/runs/2025-01-11_17-22-21
[2025-01-11 17:31:06,034][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-01-11 17:31:06,037][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-01-11 17:31:06,064][__main__][INFO] - Instantiating datamodule <src.data.custom_datamodule.T3ALDataModule>
[2025-01-11 17:31:06,548][__main__][INFO] - Instantiating model <src.models.tt_method_module.T3ALModule>
[2025-01-11 17:31:05,651][root][INFO] - Loaded coca_ViT-L-14 model config.
[2025-01-11 17:31:08,934][root][INFO] - Loading pretrained coca_ViT-L-14 weights (mscoco_finetuned_laion2B-s13B-b90k).
[2025-01-11 17:31:11,948][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/models/components/tt_method.py", line 98, in __init__
    self.avg_features = self.load_avg_features(self.avg_features_path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/models/components/tt_method.py", line 123, in load_avg_features
    with open(path, "rb") as f:
         ^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: './data/Thumos14/support_videos_features/'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/def/fewshot/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/train.py", line 57, in train
    model: LightningModule = hydra.utils.instantiate(cfg.model)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
            ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'src.models.components.tt_method.T3ALNet':
IsADirectoryError(21, 'Is a directory')
full_key: model.net
[2025-01-11 17:31:11,963][src.utils.utils][INFO] - Output dir: /home/def/fewshot/logs/train/runs/2025-01-11_17-31-05
[2025-01-11 17:56:27,798][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-01-11 17:56:27,801][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-01-11 17:56:27,831][__main__][INFO] - Instantiating datamodule <src.data.custom_datamodule.T3ALDataModule>
[2025-01-11 17:56:28,326][__main__][INFO] - Instantiating model <src.models.tt_method_module.T3ALModule>
[2025-01-11 17:56:29,296][root][INFO] - Loaded coca_ViT-L-14 model config.
[2025-01-11 17:56:33,225][root][INFO] - Loading pretrained coca_ViT-L-14 weights (mscoco_finetuned_laion2B-s13B-b90k).
[2025-01-11 17:56:36,392][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/models/components/tt_method.py", line 103, in __init__
    importlib.import_module("config.zero_shot"), dict_test_name, None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/def/fewshot/config/zero_shot.py", line 25, in <module>
    with open('splits/train_75_test_25/ActivityNet/train/split_0.list', 'r') as filehandle:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'splits/train_75_test_25/ActivityNet/train/split_0.list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/def/fewshot/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/train.py", line 57, in train
    model: LightningModule = hydra.utils.instantiate(cfg.model)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
            ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'src.models.components.tt_method.T3ALNet':
FileNotFoundError(2, 'No such file or directory')
full_key: model.net
[2025-01-11 17:56:36,396][src.utils.utils][INFO] - Output dir: /home/def/fewshot/logs/train/runs/2025-01-11_17-56-27
[2025-01-11 17:57:44,182][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-01-11 17:57:44,185][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-01-11 17:57:44,210][__main__][INFO] - Instantiating datamodule <src.data.custom_datamodule.T3ALDataModule>
[2025-01-11 17:57:44,459][__main__][INFO] - Instantiating model <src.models.tt_method_module.T3ALModule>
[2025-01-11 17:57:45,187][root][INFO] - Loaded coca_ViT-L-14 model config.
[2025-01-11 17:57:48,484][root][INFO] - Loading pretrained coca_ViT-L-14 weights (mscoco_finetuned_laion2B-s13B-b90k).
[2025-01-11 17:57:50,606][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/models/components/tt_method.py", line 103, in __init__
    importlib.import_module("config.zero_shot"), dict_test_name, None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/def/fewshot/config/zero_shot.py", line 25, in <module>
    with open('splits/train_75_test_25/ActivityNet/train/split_0.list', 'r') as filehandle:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'splits/train_75_test_25/ActivityNet/train/split_0.list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/def/fewshot/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/train.py", line 57, in train
    model: LightningModule = hydra.utils.instantiate(cfg.model)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
            ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'src.models.components.tt_method.T3ALNet':
FileNotFoundError(2, 'No such file or directory')
full_key: model.net
[2025-01-11 17:57:50,609][src.utils.utils][INFO] - Output dir: /home/def/fewshot/logs/train/runs/2025-01-11_17-57-44
[2025-01-11 17:59:41,599][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-01-11 17:59:41,602][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-01-11 17:59:41,626][__main__][INFO] - Instantiating datamodule <src.data.custom_datamodule.T3ALDataModule>
[2025-01-11 17:59:41,866][__main__][INFO] - Instantiating model <src.models.tt_method_module.T3ALModule>
[2025-01-11 17:59:42,620][root][INFO] - Loaded coca_ViT-L-14 model config.
[2025-01-11 17:59:46,230][root][INFO] - Loading pretrained coca_ViT-L-14 weights (mscoco_finetuned_laion2B-s13B-b90k).
[2025-01-11 17:59:50,204][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/models/components/tt_method.py", line 103, in __init__
    importlib.import_module("config.zero_shot"), dict_test_name, None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/def/fewshot/config/zero_shot.py", line 25, in <module>
    with open('splits/train_75_test_25/ActivityNet/train/split_0.list', 'r') as filehandle:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'splits/train_75_test_25/ActivityNet/train/split_0.list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/def/fewshot/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/train.py", line 57, in train
    model: LightningModule = hydra.utils.instantiate(cfg.model)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
            ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'src.models.components.tt_method.T3ALNet':
FileNotFoundError(2, 'No such file or directory')
full_key: model.net
[2025-01-11 17:59:50,206][src.utils.utils][INFO] - Output dir: /home/def/fewshot/logs/train/runs/2025-01-11_17-59-41
[2025-01-11 18:01:34,188][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-01-11 18:01:34,190][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-01-11 18:01:34,213][__main__][INFO] - Instantiating datamodule <src.data.custom_datamodule.T3ALDataModule>
[2025-01-11 18:01:34,482][__main__][INFO] - Instantiating model <src.models.tt_method_module.T3ALModule>
[2025-01-11 18:01:35,166][root][INFO] - Loaded coca_ViT-L-14 model config.
[2025-01-11 18:01:38,860][root][INFO] - Loading pretrained coca_ViT-L-14 weights (mscoco_finetuned_laion2B-s13B-b90k).
[2025-01-11 18:01:42,636][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/models/components/tt_method.py", line 110, in __init__
    with open(self.annotations_path, "r") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './data/thumos_annotations/thumos_anno_action.json'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/def/fewshot/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/train.py", line 57, in train
    model: LightningModule = hydra.utils.instantiate(cfg.model)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
            ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'src.models.components.tt_method.T3ALNet':
FileNotFoundError(2, 'No such file or directory')
full_key: model.net
[2025-01-11 18:01:42,638][src.utils.utils][INFO] - Output dir: /home/def/fewshot/logs/train/runs/2025-01-11_18-01-34
