[2025-01-11 16:57:13,476][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-01-11 16:57:13,478][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-01-11 16:57:13,503][__main__][INFO] - Instantiating datamodule <src.data.custom_datamodule.T3ALDataModule>
[2025-01-11 16:57:13,506][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
          ^^^^^^^^^^^^^^^^^^
AttributeError: module 'src.data' has no attribute 'custom_datamodule'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
          ^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/def/fewshot/src/data/custom_datamodule.py", line 5, in <module>
    from src.data.components.dataset import T3ALDataset
  File "/home/def/fewshot/src/data/components/dataset.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
             ^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/utils.py", line 653, in _locate
    raise ImportError(
ImportError: Error loading 'src.data.custom_datamodule.T3ALDataModule':
ModuleNotFoundError("No module named 'pandas'")
Are you sure that 'custom_datamodule' is importable from module 'src.data'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/def/fewshot/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/train.py", line 54, in train
    datamodule: LightningDataModule = hydra.utils.instantiate(cfg.data)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'src.data.custom_datamodule.T3ALDataModule', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: data
[2025-01-11 16:57:13,508][src.utils.utils][INFO] - Output dir: /home/def/fewshot/logs/train/runs/2025-01-11_16-57-13
[2025-01-11 16:57:47,829][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-01-11 16:57:47,831][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-01-11 16:57:47,852][__main__][INFO] - Instantiating datamodule <src.data.custom_datamodule.T3ALDataModule>
[2025-01-11 16:57:48,204][__main__][INFO] - Instantiating model <src.models.tt_method_module.T3ALModule>
[2025-01-11 16:57:48,647][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
          ^^^^^^^^^^^^^^^^^^
AttributeError: module 'src.models' has no attribute 'tt_method_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
          ^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/def/fewshot/src/models/tt_method_module.py", line 8, in <module>
    from src.evaluate import evaluate
  File "/home/def/fewshot/src/evaluate.py", line 8, in <module>
    from tabulate import tabulate
ModuleNotFoundError: No module named 'tabulate'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
             ^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/utils.py", line 653, in _locate
    raise ImportError(
ImportError: Error loading 'src.models.tt_method_module.T3ALModule':
ModuleNotFoundError("No module named 'tabulate'")
Are you sure that 'tt_method_module' is importable from module 'src.models'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/def/fewshot/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/train.py", line 57, in train
    model: LightningModule = hydra.utils.instantiate(cfg.model)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'src.models.tt_method_module.T3ALModule', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: model
[2025-01-11 16:57:48,649][src.utils.utils][INFO] - Output dir: /home/def/fewshot/logs/train/runs/2025-01-11_16-57-47
[2025-01-11 16:58:37,384][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-01-11 16:58:37,386][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-01-11 16:58:37,409][__main__][INFO] - Instantiating datamodule <src.data.custom_datamodule.T3ALDataModule>
[2025-01-11 16:58:37,667][__main__][INFO] - Instantiating model <src.models.tt_method_module.T3ALModule>
[2025-01-11 16:58:38,421][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: T3ALNet.__init__() missing 1 required positional argument: 'avg_features_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/def/fewshot/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/train.py", line 57, in train
    model: LightningModule = hydra.utils.instantiate(cfg.model)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
            ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'src.models.components.tt_method.T3ALNet':
TypeError("T3ALNet.__init__() missing 1 required positional argument: 'avg_features_path'")
full_key: model.net
[2025-01-11 16:58:38,422][src.utils.utils][INFO] - Output dir: /home/def/fewshot/logs/train/runs/2025-01-11_16-58-37
[2025-01-11 17:03:27,561][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-01-11 17:03:27,564][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-01-11 17:03:27,588][__main__][INFO] - Instantiating datamodule <src.data.custom_datamodule.T3ALDataModule>
[2025-01-11 17:03:27,854][__main__][INFO] - Instantiating model <src.models.tt_method_module.T3ALModule>
[2025-01-11 17:03:28,566][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: T3ALNet.__init__() missing 1 required positional argument: 'avg_features_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/def/fewshot/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/train.py", line 57, in train
    model: LightningModule = hydra.utils.instantiate(cfg.model)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
            ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'src.models.components.tt_method.T3ALNet':
TypeError("T3ALNet.__init__() missing 1 required positional argument: 'avg_features_path'")
full_key: model.net
[2025-01-11 17:03:28,567][src.utils.utils][INFO] - Output dir: /home/def/fewshot/logs/train/runs/2025-01-11_17-03-27
[2025-01-11 17:10:43,684][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-01-11 17:10:43,687][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-01-11 17:10:43,717][__main__][INFO] - Instantiating datamodule <src.data.custom_datamodule.T3ALDataModule>
[2025-01-11 17:10:44,187][__main__][INFO] - Instantiating model <src.models.tt_method_module.T3ALModule>
[2025-01-11 17:10:45,127][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: T3ALNet.__init__() missing 1 required positional argument: 'avg_features_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/def/fewshot/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/train.py", line 57, in train
    model: LightningModule = hydra.utils.instantiate(cfg.model)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
            ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'src.models.components.tt_method.T3ALNet':
TypeError("T3ALNet.__init__() missing 1 required positional argument: 'avg_features_path'")
full_key: model.net
[2025-01-11 17:10:45,128][src.utils.utils][INFO] - Output dir: /home/def/fewshot/logs/train/runs/2025-01-11_17-10-43
[2025-01-11 17:22:21,427][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-01-11 17:22:21,430][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-01-11 17:22:21,458][__main__][INFO] - Instantiating datamodule <src.data.custom_datamodule.T3ALDataModule>
[2025-01-11 17:22:21,933][__main__][INFO] - Instantiating model <src.models.tt_method_module.T3ALModule>
[2025-01-11 17:22:22,893][root][INFO] - Loaded coca_ViT-L-14 model config.
[2025-01-11 17:22:26,529][root][INFO] - Loading pretrained coca_ViT-L-14 weights (mscoco_finetuned_laion2B-s13B-b90k).
[2025-01-11 17:22:27,982][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/models/components/tt_method.py", line 83, in __init__
    self.video_dir = os.path.join(self.video_path, "Thumos14/videos/")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/def/fewshot/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/train.py", line 57, in train
    model: LightningModule = hydra.utils.instantiate(cfg.model)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
            ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'src.models.components.tt_method.T3ALNet':
TypeError('expected str, bytes or os.PathLike object, not NoneType')
full_key: model.net
[2025-01-11 17:22:27,984][src.utils.utils][INFO] - Output dir: /home/def/fewshot/logs/train/runs/2025-01-11_17-22-21
[2025-01-11 17:31:06,034][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-01-11 17:31:06,037][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-01-11 17:31:06,064][__main__][INFO] - Instantiating datamodule <src.data.custom_datamodule.T3ALDataModule>
[2025-01-11 17:31:06,548][__main__][INFO] - Instantiating model <src.models.tt_method_module.T3ALModule>
[2025-01-11 17:31:05,651][root][INFO] - Loaded coca_ViT-L-14 model config.
[2025-01-11 17:31:08,934][root][INFO] - Loading pretrained coca_ViT-L-14 weights (mscoco_finetuned_laion2B-s13B-b90k).
[2025-01-11 17:31:11,948][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/models/components/tt_method.py", line 98, in __init__
    self.avg_features = self.load_avg_features(self.avg_features_path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/models/components/tt_method.py", line 123, in load_avg_features
    with open(path, "rb") as f:
         ^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: './data/Thumos14/support_videos_features/'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/def/fewshot/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/train.py", line 57, in train
    model: LightningModule = hydra.utils.instantiate(cfg.model)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
            ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'src.models.components.tt_method.T3ALNet':
IsADirectoryError(21, 'Is a directory')
full_key: model.net
[2025-01-11 17:31:11,963][src.utils.utils][INFO] - Output dir: /home/def/fewshot/logs/train/runs/2025-01-11_17-31-05
[2025-01-11 17:56:27,798][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-01-11 17:56:27,801][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-01-11 17:56:27,831][__main__][INFO] - Instantiating datamodule <src.data.custom_datamodule.T3ALDataModule>
[2025-01-11 17:56:28,326][__main__][INFO] - Instantiating model <src.models.tt_method_module.T3ALModule>
[2025-01-11 17:56:29,296][root][INFO] - Loaded coca_ViT-L-14 model config.
[2025-01-11 17:56:33,225][root][INFO] - Loading pretrained coca_ViT-L-14 weights (mscoco_finetuned_laion2B-s13B-b90k).
[2025-01-11 17:56:36,392][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/models/components/tt_method.py", line 103, in __init__
    importlib.import_module("config.zero_shot"), dict_test_name, None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/def/fewshot/config/zero_shot.py", line 25, in <module>
    with open('splits/train_75_test_25/ActivityNet/train/split_0.list', 'r') as filehandle:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'splits/train_75_test_25/ActivityNet/train/split_0.list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/def/fewshot/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/train.py", line 57, in train
    model: LightningModule = hydra.utils.instantiate(cfg.model)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
            ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'src.models.components.tt_method.T3ALNet':
FileNotFoundError(2, 'No such file or directory')
full_key: model.net
[2025-01-11 17:56:36,396][src.utils.utils][INFO] - Output dir: /home/def/fewshot/logs/train/runs/2025-01-11_17-56-27
[2025-01-11 17:57:44,182][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-01-11 17:57:44,185][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-01-11 17:57:44,210][__main__][INFO] - Instantiating datamodule <src.data.custom_datamodule.T3ALDataModule>
[2025-01-11 17:57:44,459][__main__][INFO] - Instantiating model <src.models.tt_method_module.T3ALModule>
[2025-01-11 17:57:45,187][root][INFO] - Loaded coca_ViT-L-14 model config.
[2025-01-11 17:57:48,484][root][INFO] - Loading pretrained coca_ViT-L-14 weights (mscoco_finetuned_laion2B-s13B-b90k).
[2025-01-11 17:57:50,606][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/models/components/tt_method.py", line 103, in __init__
    importlib.import_module("config.zero_shot"), dict_test_name, None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/def/fewshot/config/zero_shot.py", line 25, in <module>
    with open('splits/train_75_test_25/ActivityNet/train/split_0.list', 'r') as filehandle:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'splits/train_75_test_25/ActivityNet/train/split_0.list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/def/fewshot/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/train.py", line 57, in train
    model: LightningModule = hydra.utils.instantiate(cfg.model)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
            ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'src.models.components.tt_method.T3ALNet':
FileNotFoundError(2, 'No such file or directory')
full_key: model.net
[2025-01-11 17:57:50,609][src.utils.utils][INFO] - Output dir: /home/def/fewshot/logs/train/runs/2025-01-11_17-57-44
[2025-01-11 17:59:41,599][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-01-11 17:59:41,602][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-01-11 17:59:41,626][__main__][INFO] - Instantiating datamodule <src.data.custom_datamodule.T3ALDataModule>
[2025-01-11 17:59:41,866][__main__][INFO] - Instantiating model <src.models.tt_method_module.T3ALModule>
[2025-01-11 17:59:42,620][root][INFO] - Loaded coca_ViT-L-14 model config.
[2025-01-11 17:59:46,230][root][INFO] - Loading pretrained coca_ViT-L-14 weights (mscoco_finetuned_laion2B-s13B-b90k).
[2025-01-11 17:59:50,204][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/models/components/tt_method.py", line 103, in __init__
    importlib.import_module("config.zero_shot"), dict_test_name, None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/def/fewshot/config/zero_shot.py", line 25, in <module>
    with open('splits/train_75_test_25/ActivityNet/train/split_0.list', 'r') as filehandle:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'splits/train_75_test_25/ActivityNet/train/split_0.list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/def/fewshot/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/train.py", line 57, in train
    model: LightningModule = hydra.utils.instantiate(cfg.model)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
            ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'src.models.components.tt_method.T3ALNet':
FileNotFoundError(2, 'No such file or directory')
full_key: model.net
[2025-01-11 17:59:50,206][src.utils.utils][INFO] - Output dir: /home/def/fewshot/logs/train/runs/2025-01-11_17-59-41
[2025-01-11 18:01:34,188][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-01-11 18:01:34,190][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-01-11 18:01:34,213][__main__][INFO] - Instantiating datamodule <src.data.custom_datamodule.T3ALDataModule>
[2025-01-11 18:01:34,482][__main__][INFO] - Instantiating model <src.models.tt_method_module.T3ALModule>
[2025-01-11 18:01:35,166][root][INFO] - Loaded coca_ViT-L-14 model config.
[2025-01-11 18:01:38,860][root][INFO] - Loading pretrained coca_ViT-L-14 weights (mscoco_finetuned_laion2B-s13B-b90k).
[2025-01-11 18:01:42,636][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/models/components/tt_method.py", line 110, in __init__
    with open(self.annotations_path, "r") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './data/thumos_annotations/thumos_anno_action.json'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/def/fewshot/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/train.py", line 57, in train
    model: LightningModule = hydra.utils.instantiate(cfg.model)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
            ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'src.models.components.tt_method.T3ALNet':
FileNotFoundError(2, 'No such file or directory')
full_key: model.net
[2025-01-11 18:01:42,638][src.utils.utils][INFO] - Output dir: /home/def/fewshot/logs/train/runs/2025-01-11_18-01-34
[2025-01-11 18:04:34,509][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-01-11 18:04:34,512][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-01-11 18:04:34,535][__main__][INFO] - Instantiating datamodule <src.data.custom_datamodule.T3ALDataModule>
[2025-01-11 18:04:34,775][__main__][INFO] - Instantiating model <src.models.tt_method_module.T3ALModule>
[2025-01-11 18:04:35,490][root][INFO] - Loaded coca_ViT-L-14 model config.
[2025-01-11 18:04:39,226][root][INFO] - Loading pretrained coca_ViT-L-14 weights (mscoco_finetuned_laion2B-s13B-b90k).
[2025-01-11 18:04:41,465][__main__][INFO] - Instantiating callbacks...
[2025-01-11 18:04:41,466][src.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.ModelCheckpoint>
[2025-01-11 18:04:41,469][src.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichModelSummary>
[2025-01-11 18:04:41,469][src.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichProgressBar>
[2025-01-11 18:04:41,469][__main__][INFO] - Instantiating loggers...
[2025-01-11 18:04:41,470][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2025-01-11 18:04:41,472][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2025-01-11 18:04:41,613][__main__][INFO] - Logging hyperparameters!
[2025-01-11 18:05:06,281][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/def/fewshot/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/train.py", line 85, in train
    utils.log_hyperparameters(object_dict)
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning_utilities/core/rank_zero.py", line 42, in wrapped_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/utils/logging_utils.py", line 51, in log_hyperparameters
    logger.log_hyperparams(hparams)
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning_utilities/core/rank_zero.py", line 42, in wrapped_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/loggers/wandb.py", line 429, in log_hyperparams
    self.experiment.config.update(params, allow_val_change=True)
    ^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/fabric/loggers/logger.py", line 118, in experiment
    return fn(self)
           ^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/loggers/wandb.py", line 407, in experiment
    self._experiment = wandb.init(**self._wandb_init)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1303, in init
    wandb._sentry.reraise(e)
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/wandb/analytics/sentry.py", line 156, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1289, in init
    return wi.init()
           ^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 821, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 277, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
[2025-01-11 18:05:06,284][src.utils.utils][INFO] - Output dir: /home/def/fewshot/logs/train/runs/2025-01-11_18-04-34
[2025-01-11 18:20:27,363][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-01-11 18:20:27,365][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-01-11 18:20:27,395][__main__][INFO] - Instantiating datamodule <src.data.custom_datamodule.T3ALDataModule>
[2025-01-11 18:20:27,872][__main__][INFO] - Instantiating model <src.models.tt_method_module.T3ALModule>
[2025-01-11 18:20:28,925][root][INFO] - Loaded coca_ViT-L-14 model config.
[2025-01-11 18:20:32,220][root][INFO] - Loading pretrained coca_ViT-L-14 weights (mscoco_finetuned_laion2B-s13B-b90k).
[2025-01-11 18:20:35,624][__main__][INFO] - Instantiating callbacks...
[2025-01-11 18:20:35,624][src.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.ModelCheckpoint>
[2025-01-11 18:20:35,629][src.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichModelSummary>
[2025-01-11 18:20:35,629][src.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichProgressBar>
[2025-01-11 18:20:35,630][__main__][INFO] - Instantiating loggers...
[2025-01-11 18:20:35,630][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2025-01-11 18:20:35,633][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2025-01-11 18:20:35,752][__main__][INFO] - Logging hyperparameters!
[2025-01-11 18:20:35,758][__main__][INFO] - Starting training!
[2025-01-11 18:20:38,017][__main__][INFO] - Starting testing!
[2025-01-11 18:20:38,017][__main__][WARNING] - Best ckpt not found! Using current weights for testing...
[2025-01-11 18:20:40,365][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/def/fewshot/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/train.py", line 103, in train
    trainer.test(model=model, datamodule=datamodule, ckpt_path=ckpt_path)
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 749, in test
    return call._call_and_handle_interrupt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 47, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 789, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 982, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1019, in _run_stage
    return self._evaluation_loop.run()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/loops/utilities.py", line 179, in _decorator
    return loop_run(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 137, in run
    batch, batch_idx, dataloader_idx = next(data_fetcher)
                                       ^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/loops/fetchers.py", line 134, in __next__
    batch = super().__next__()
            ^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/loops/fetchers.py", line 61, in __next__
    batch = next(self.iterator)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/utilities/combined_loader.py", line 341, in __next__
    out = next(self._iterator)
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/utilities/combined_loader.py", line 142, in __next__
    out = next(self.iterators[0])
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1465, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1491, in _process_data
    data.reraise()
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/torch/_utils.py", line 715, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 351, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/home/def/fewshot/src/data/components/dataset.py", line 74, in __getitem__
    video_idx, video = self.baselinegetFeatureData(index)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/data/components/dataset.py", line 39, in baselinegetFeatureData
    video = self.loadFeature(video_idx)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/data/components/dataset.py", line 94, in loadFeature
    video_data = np.load(os.path.join(self.feature_path, idx + ".npy"))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './data/Thumos14/features/video_validation_0000365.npy'

[2025-01-11 18:20:40,381][src.utils.utils][INFO] - Output dir: /home/def/fewshot/logs/train/runs/2025-01-11_18-20-27
[2025-01-11 18:20:40,381][src.utils.utils][INFO] - Closing wandb!
[2025-01-11 18:22:14,129][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-01-11 18:22:14,132][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-01-11 18:22:14,160][__main__][INFO] - Instantiating datamodule <src.data.custom_datamodule.T3ALDataModule>
[2025-01-11 18:22:14,651][__main__][INFO] - Instantiating model <src.models.tt_method_module.T3ALModule>
[2025-01-11 18:22:15,719][root][INFO] - Loaded coca_ViT-L-14 model config.
[2025-01-11 18:22:19,505][root][INFO] - Loading pretrained coca_ViT-L-14 weights (mscoco_finetuned_laion2B-s13B-b90k).
[2025-01-11 18:22:22,429][__main__][INFO] - Instantiating callbacks...
[2025-01-11 18:22:22,429][src.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.ModelCheckpoint>
[2025-01-11 18:22:22,431][src.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichModelSummary>
[2025-01-11 18:22:22,431][src.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichProgressBar>
[2025-01-11 18:22:22,432][__main__][INFO] - Instantiating loggers...
[2025-01-11 18:22:22,432][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2025-01-11 18:22:22,434][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2025-01-11 18:22:22,537][__main__][INFO] - Logging hyperparameters!
[2025-01-11 18:22:22,541][__main__][INFO] - Starting training!
[2025-01-11 18:22:24,598][__main__][INFO] - Starting testing!
[2025-01-11 18:22:24,599][__main__][WARNING] - Best ckpt not found! Using current weights for testing...
[2025-01-11 18:22:26,968][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/def/fewshot/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/train.py", line 103, in train
    trainer.test(model=model, datamodule=datamodule, ckpt_path=ckpt_path)
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 749, in test
    return call._call_and_handle_interrupt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 47, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 789, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 982, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1019, in _run_stage
    return self._evaluation_loop.run()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/loops/utilities.py", line 179, in _decorator
    return loop_run(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 144, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 433, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 323, in _call_strategy_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/strategies/strategy.py", line 425, in test_step
    return self.lightning_module.test_step(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/models/tt_method_module.py", line 105, in test_step
    self.model_step(
  File "/home/def/fewshot/src/models/tt_method_module.py", line 83, in model_step
    return self.forward(batch, opt)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/models/tt_method_module.py", line 77, in forward
    return self.net(x, opt)
           ^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/models/components/tt_method.py", line 346, in forward
    fps = self.get_video_fps(video_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/models/components/tt_method.py", line 210, in get_video_fps
    return fps
           ^^^
UnboundLocalError: cannot access local variable 'fps' where it is not associated with a value
[2025-01-11 18:22:26,975][src.utils.utils][INFO] - Output dir: /home/def/fewshot/logs/train/runs/2025-01-11_18-22-14
[2025-01-11 18:22:26,975][src.utils.utils][INFO] - Closing wandb!
[2025-01-11 18:30:51,718][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-01-11 18:30:51,721][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-01-11 18:30:51,748][__main__][INFO] - Instantiating datamodule <src.data.custom_datamodule.T3ALDataModule>
[2025-01-11 18:30:52,192][__main__][INFO] - Instantiating model <src.models.tt_method_module.T3ALModule>
[2025-01-11 18:30:53,243][root][INFO] - Loaded coca_ViT-L-14 model config.
[2025-01-11 18:30:56,196][root][INFO] - Loading pretrained coca_ViT-L-14 weights (mscoco_finetuned_laion2B-s13B-b90k).
[2025-01-11 18:30:58,525][__main__][INFO] - Instantiating callbacks...
[2025-01-11 18:30:58,526][src.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.ModelCheckpoint>
[2025-01-11 18:30:58,528][src.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichModelSummary>
[2025-01-11 18:30:58,529][src.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichProgressBar>
[2025-01-11 18:30:58,529][__main__][INFO] - Instantiating loggers...
[2025-01-11 18:30:58,529][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2025-01-11 18:30:58,531][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2025-01-11 18:30:58,663][__main__][INFO] - Logging hyperparameters!
[2025-01-11 18:30:58,669][__main__][INFO] - Starting training!
[2025-01-11 18:31:01,048][__main__][INFO] - Starting testing!
[2025-01-11 18:31:01,048][__main__][WARNING] - Best ckpt not found! Using current weights for testing...
[2025-01-11 18:31:06,804][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/def/fewshot/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/train.py", line 103, in train
    trainer.test(model=model, datamodule=datamodule, ckpt_path=ckpt_path)
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 749, in test
    return call._call_and_handle_interrupt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 47, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 789, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 982, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1019, in _run_stage
    return self._evaluation_loop.run()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/loops/utilities.py", line 179, in _decorator
    return loop_run(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 144, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 433, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 323, in _call_strategy_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/strategies/strategy.py", line 425, in test_step
    return self.lightning_module.test_step(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/models/tt_method_module.py", line 105, in test_step
    self.model_step(
  File "/home/def/fewshot/src/models/tt_method_module.py", line 83, in model_step
    return self.forward(batch, opt)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/models/tt_method_module.py", line 77, in forward
    return self.net(x, opt)
           ^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/models/components/tt_method.py", line 481, in forward
    with open(f"./data/Thumos14/captions/{video_name}.txt", "r", encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './data/Thumos14/captions/video_validation_0000365.txt'
[2025-01-11 18:31:06,811][src.utils.utils][INFO] - Output dir: /home/def/fewshot/logs/train/runs/2025-01-11_18-30-51
[2025-01-11 18:31:06,811][src.utils.utils][INFO] - Closing wandb!
[2025-01-11 18:32:30,380][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-01-11 18:32:30,382][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-01-11 18:32:30,407][__main__][INFO] - Instantiating datamodule <src.data.custom_datamodule.T3ALDataModule>
[2025-01-11 18:32:30,641][__main__][INFO] - Instantiating model <src.models.tt_method_module.T3ALModule>
[2025-01-11 18:32:31,482][root][INFO] - Loaded coca_ViT-L-14 model config.
[2025-01-11 18:32:34,825][root][INFO] - Loading pretrained coca_ViT-L-14 weights (mscoco_finetuned_laion2B-s13B-b90k).
[2025-01-11 18:32:38,101][__main__][INFO] - Instantiating callbacks...
[2025-01-11 18:32:38,102][src.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.ModelCheckpoint>
[2025-01-11 18:32:38,105][src.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichModelSummary>
[2025-01-11 18:32:38,106][src.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichProgressBar>
[2025-01-11 18:32:38,106][__main__][INFO] - Instantiating loggers...
[2025-01-11 18:32:38,106][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2025-01-11 18:32:38,110][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2025-01-11 18:32:38,229][__main__][INFO] - Logging hyperparameters!
[2025-01-11 18:32:38,234][__main__][INFO] - Starting training!
[2025-01-11 18:32:40,675][__main__][INFO] - Starting testing!
[2025-01-11 18:32:40,676][__main__][WARNING] - Best ckpt not found! Using current weights for testing...
[2025-01-11 18:49:43,309][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/def/fewshot/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/train.py", line 103, in train
    trainer.test(model=model, datamodule=datamodule, ckpt_path=ckpt_path)
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 749, in test
    return call._call_and_handle_interrupt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 47, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 789, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 982, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1019, in _run_stage
    return self._evaluation_loop.run()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/loops/utilities.py", line 179, in _decorator
    return loop_run(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 151, in run
    return self.on_run_end()
           ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 291, in on_run_end
    self._on_evaluation_epoch_end()
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 371, in _on_evaluation_epoch_end
    call._call_lightning_module_hook(trainer, hook_name)
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 171, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/models/tt_method_module.py", line 126, in on_test_epoch_end
    aps, tious = evaluate(self.dataset, self.predictions, self.split, self.setting, self.video_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/evaluate.py", line 148, in evaluate
    video_dir = video_path + "Thumos14/videos/"
                ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
[2025-01-11 18:49:43,313][src.utils.utils][INFO] - Output dir: /home/def/fewshot/logs/train/runs/2025-01-11_18-32-30
[2025-01-11 18:49:43,313][src.utils.utils][INFO] - Closing wandb!
[2025-01-11 21:05:24,227][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-01-11 21:05:24,229][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-01-11 21:05:24,255][__main__][INFO] - Instantiating datamodule <src.data.custom_datamodule.T3ALDataModule>
[2025-01-11 21:05:24,734][__main__][INFO] - Instantiating model <src.models.tt_method_module.T3ALModule>
[2025-01-11 21:05:25,736][root][INFO] - Loaded coca_ViT-L-14 model config.
[2025-01-11 21:05:29,547][root][INFO] - Loading pretrained coca_ViT-L-14 weights (mscoco_finetuned_laion2B-s13B-b90k).
[2025-01-11 21:05:33,042][__main__][INFO] - Instantiating callbacks...
[2025-01-11 21:05:33,043][src.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.ModelCheckpoint>
[2025-01-11 21:05:33,045][src.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichModelSummary>
[2025-01-11 21:05:33,045][src.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichProgressBar>
[2025-01-11 21:05:33,045][__main__][INFO] - Instantiating loggers...
[2025-01-11 21:05:33,045][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2025-01-11 21:05:33,047][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2025-01-11 21:05:33,159][__main__][INFO] - Logging hyperparameters!
[2025-01-11 21:05:33,163][__main__][INFO] - Starting training!
[2025-01-11 21:05:35,027][__main__][INFO] - Starting testing!
[2025-01-11 21:05:35,028][__main__][WARNING] - Best ckpt not found! Using current weights for testing...
[2025-01-11 21:18:47,150][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/def/fewshot/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/train.py", line 103, in train
    trainer.test(model=model, datamodule=datamodule, ckpt_path=ckpt_path)
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 749, in test
    return call._call_and_handle_interrupt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 47, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 789, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 982, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1019, in _run_stage
    return self._evaluation_loop.run()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/loops/utilities.py", line 179, in _decorator
    return loop_run(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 151, in run
    return self.on_run_end()
           ^^^^^^^^^^^^^^^^^
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 291, in on_run_end
    self._on_evaluation_epoch_end()
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 371, in _on_evaluation_epoch_end
    call._call_lightning_module_hook(trainer, hook_name)
  File "/home/def/miniforge3/envs/fewshot/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 171, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/models/tt_method_module.py", line 126, in on_test_epoch_end
    aps, tious = evaluate(self.dataset, self.predictions, self.split, self.setting, self.video_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/def/fewshot/src/evaluate.py", line 148, in evaluate
    video_dir = video_path + "Thumos14/videos/"
                ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
[2025-01-11 21:18:47,153][src.utils.utils][INFO] - Output dir: /home/def/fewshot/logs/train/runs/2025-01-11_21-05-24
[2025-01-11 21:18:47,154][src.utils.utils][INFO] - Closing wandb!
[2025-01-11 21:26:14,195][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-01-11 21:26:14,197][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-01-11 21:26:14,223][__main__][INFO] - Instantiating datamodule <src.data.custom_datamodule.T3ALDataModule>
[2025-01-11 21:26:14,594][__main__][INFO] - Instantiating model <src.models.tt_method_module.T3ALModule>
[2025-01-11 21:26:15,583][root][INFO] - Loaded coca_ViT-L-14 model config.
[2025-01-11 21:26:19,104][root][INFO] - Loading pretrained coca_ViT-L-14 weights (mscoco_finetuned_laion2B-s13B-b90k).
[2025-01-11 21:26:22,810][__main__][INFO] - Instantiating callbacks...
[2025-01-11 21:26:22,811][src.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.ModelCheckpoint>
[2025-01-11 21:26:22,814][src.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichModelSummary>
[2025-01-11 21:26:22,815][src.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichProgressBar>
[2025-01-11 21:26:22,815][__main__][INFO] - Instantiating loggers...
[2025-01-11 21:26:22,816][src.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2025-01-11 21:26:22,818][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2025-01-11 21:26:22,925][__main__][INFO] - Logging hyperparameters!
[2025-01-11 21:26:22,930][__main__][INFO] - Starting training!
[2025-01-11 21:26:25,100][__main__][INFO] - Starting testing!
[2025-01-11 21:26:25,101][__main__][WARNING] - Best ckpt not found! Using current weights for testing...
